server:
  port: 8080
spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    register-with-eureka: false
management:
  endpoints:
    web:
      exposure:
        include: '*'