server:
  port: 9092
spring:
  sleuth:
    sampler:
      probability: 1
  application:
    name: service-b
  zipkin:
    base-url: http://localhost:9411/
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'